// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lineup-glass/LineupGlass.tsx": () => import("../components/mockups/lineup-glass/LineupGlass.tsx")
};
